"""add model Follow

Revision ID: ef822164dbc2
Revises: 8935d2fa03e5
Create Date: 2018-02-02 22:02:13.626116

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ef822164dbc2'
down_revision = '8935d2fa03e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
                    sa.Column('followed_id', sa.Integer(), nullable=False),
                    sa.Column('follower_id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('followed_id', 'follower_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
